### ISSUE TITLE
Feature Request: Display surfaces in volume space without loading a volume

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#51]
If I load surfaces right now without an accompanying volume, I don't get a "volume" view, so I can't compare surfaces easily.

**Comment by rdvincent** [comment]
So you would like Display to create a "blank" slice view window that just shows the outlines of the surfaces for each axis? This could be addressed by creating a dummy placeholder volume with coordinates that matched the extents of the loaded surfaces.

**Comment by gdevenyi** [comment]
Yes, I'd like a slice view of the objects if a volume isn't available.

**Comment by rdvincent** [comment]
@gdevenyi Do you care about what the background is? Should it be black, the lovely background colour, grey, etc.? Here's what I have right now with a black background, because the empty volume effectively has a uniform value of zero:
![image](https://cloud.githubusercontent.com/assets/1395526/15158578/9453defe-16be-11e6-9d00-b88858cc9bfc.png)

**Comment by gdevenyi** [comment]
The current colour is fine except if someone decides to segment in teal... perhaps it should be linked to the background colour of the volume?

**Comment by rdvincent** [comment]
@gdevenyi Well, in this case I'm just looking for a preference for the default slice background (currently black, above) against which the surfaces will be displayed.

**Comment by gdevenyi** [comment]
oh, sorry, I misinterpreted, yes, black is fine.

**Comment by rdvincent** [comment]
@gdevenyi OK this is checked in.

**Comment by gdevenyi** [comment]
Looks great, thanks!
