### ISSUE TITLE
"Load" vertstats file as surface label?

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#67]
I have a vertstats file I'd like to use a "label" set, rather than a continuous statistics set.

Loading it with the regular method doesn't look nice, as the labels cover a wide range and don't map nicely to a continuous display.

Display now has manual "surface segmentation", is there a possibility of loading a verstats file as a surface segmentation rather than as statistics?

**Comment by rdvincent** [comment]
@gdevenyi So like the volumetric labels, integer values (I hope they are integers) on the vertices would map to specific colours, rather than a continuous colour map?

**Comment by gdevenyi** [comment]
Correct

**Comment by rdvincent** [comment]
@gdevenyi This is now possible with GIFTI "label" files, as they can contain colour map information. Can you give me an example of a vertstats file that would have this type of data? I'm curious to see what, if any, metadata is present. Otherwise I can just have a special case that uses a discrete colour map if integer data is detected.

**Comment by gdevenyi** [comment]
The AAL, DKT, lobe maps from CIVET.

**Comment by gdevenyi** [comment]
And these https://github.com/CobraLab/atlases/tree/master/colin27-subcortical/surfaces

**Comment by gdevenyi** [comment]
Using this and generally it looks great, one issue, the value "0" should probably be treated special.

Right now, it gets considered and assigned a colour, I think it should probably be the object base colour.
